### ISSUE TITLE
select on multiple tables shows only one column 'id'

### ISSUE THREAD

**Issue by kwollw** [wi-wissen/InstaHub#5]
login into any student's hub
goto sql

select users.id, username, photos.id, description from users, photos
>>>
id	username	description
1	admin	        #eibrot #ei #brot
...
There is only one column id which is the id from photos.

should be:
users.id     username    photos.id    description

The correct function is essentially for teaching joins through an approach that derives joins from the Cartesian product of the tables.

workaround:
alias the ids:
select users.id u_id, username, photos.id, p_id, description from users, photos
>>>
u_id	username	p_id	 description
204	admin	       1	 #eibrot #ei #brot
...
(Don't use alias user_id since it is foreign key in table photos)

**Comment by wi-wissen** [comment]
The behaviour is predefined by the framework. As the owner @taylorotwell said in https://github.com/laravel/ideas/issues/347, this is intended. The mentioned workaround solves the problem.

```sql
select users.id as 'users.id', username, photos.id as 'photos.id', description 
from users, photos 
limit 10
```

Even if phpMyAdmin, for example, handles this differently, the behavior is not so unusual from the student's point of view, since there would be confusion in the table as to which ID is which.
